#!/bin/sh

mktpm2() {
	d=$(mktemp -d)
	ln -s $d .tpm2
}

[ -d .tpm2 ] || mktpm2
if [ -f .tpm2/pid ]; then
    kill -9 $(<.tpm2/pid) || true
    rm .tpm2/pid
fi
rm -f .tpm2/swtpm-sock
swtpm socket --tpmstate dir=.tpm2 --tpm2 \
    --ctrl type=unixio,path=.tpm2/swtpm-sock \
    --pid file=.tpm2/pid &
while [ ! -e .tpm2/swtpm-sock ]; do sleep 1; done
